export type BlogPost = {
  title: string;
  excerpt: string;
  date: string;
  category: string;
  slug: string;
  readTime: string;
  content: Section[];
};

export type Section = {
  type: "h2" | "h3" | "p" | "code" | "ul" | "ol" | "callout";
  text?: string;
  items?: string[];
  language?: string;
};

export const blogPosts: BlogPost[] = [
  {
    title: "How I Built an Auto Insurance Fraud Detection System with 93% ROC-AUC",
    excerpt:
      "A walkthrough of my end-to-end fraud detection project — from raw insurance claims data to a deployed Streamlit app. Covers EDA, feature engineering, and ensemble model comparisons including XGBoost and Extra Trees.",
    date: "Jan 20, 2025",
    category: "Machine Learning",
    slug: "auto-fraud-detection-system",
    readTime: "9 min read",
    content: [
      { type: "p", text: "Insurance fraud costs the industry billions every year. When I started this project, my goal was simple: could I build a model accurate enough to flag suspicious claims before a human investigator ever looks at them?" },
      { type: "h2", text: "The Dataset" },
      { type: "p", text: "I worked with a publicly available auto insurance claims dataset containing ~15,000 records. Each row represented a single claim, with features ranging from policy details (premium amount, coverage type, deductible) to incident specifics (collision type, property damage, police report filed) and claimant demographics." },
      { type: "p", text: "The target variable was binary: fraudulent (1) or legitimate (0). The dataset was imbalanced — only about 24% of claims were fraudulent — which immediately told me that accuracy alone would be a misleading metric." },
      { type: "h2", text: "Exploratory Data Analysis" },
      { type: "p", text: "Before touching a model, I spent time understanding the data. A few findings stood out immediately:" },
      { type: "ul", items: ["Claims filed without a police report were 2.3× more likely to be fraudulent.", "Policy holders with 5+ years tenure had significantly lower fraud rates.", "Certain incident types (e.g., multi-vehicle collisions with no witnesses) had fraud rates above 40%.", "The 'property damage' and 'bodily injuries' fields showed clear separation between fraud and non-fraud distributions."] },
      { type: "h2", text: "Feature Engineering" },
      { type: "p", text: "Raw features rarely tell the full story. I created several derived features:" },
      { type: "ul", items: ["claim_to_premium_ratio: total claim amount divided by annual premium — high ratios are a red flag.", "days_since_policy_start: claims filed very early in a policy's life are suspicious.", "incident_severity_score: a composite of injury count, vehicle damage, and property damage.", "is_weekend_incident: fraud claims skewed toward weekends in this dataset."] },
      { type: "h2", text: "Model Comparisons" },
      { type: "p", text: "I trained and evaluated five classifiers, all tuned with 5-fold stratified cross-validation:" },
      { type: "ul", items: ["Logistic Regression — ROC-AUC: 0.71", "Decision Tree — ROC-AUC: 0.78", "K-Nearest Neighbours — ROC-AUC: 0.74", "XGBoost — ROC-AUC: 0.91", "Extra Trees — ROC-AUC: 0.9305 ✓"] },
      { type: "p", text: "Extra Trees edged out XGBoost slightly, primarily because its randomised split selection acted as an implicit regulariser on the noisy, imbalanced data." },
      { type: "h2", text: "Handling Class Imbalance" },
      { type: "p", text: "I used SMOTE (Synthetic Minority Oversampling Technique) on the training split only — never on the validation or test sets. This is a common mistake that inflates metrics. After applying SMOTE, the Extra Trees model's recall on the minority (fraud) class improved from 0.61 to 0.78 with only a marginal drop in precision." },
      { type: "h2", text: "Deployment with Streamlit" },
      { type: "p", text: "The final model was serialised with joblib and wrapped in a Streamlit app. Users input claim details via a form, and the app returns a fraud probability score along with a SHAP waterfall chart explaining the top contributing features. This made the model interpretable to non-technical stakeholders." },
      { type: "h2", text: "Key Takeaways" },
      { type: "ul", items: ["Never evaluate on accuracy alone with imbalanced data. Use ROC-AUC, F1, and confusion matrices.", "Feature engineering often matters more than model selection.", "SMOTE must only be applied to training data.", "SHAP values are invaluable for making black-box models explainable."] },
    ],
  },
  {
    title: "EDA on Insurance Claims: Spotting Fraud Before the Model Does",
    excerpt:
      "Before throwing data at a model, thorough exploratory data analysis tells a story. Here's how I used Pandas and Seaborn to uncover hidden patterns and class imbalances in auto insurance claims.",
    date: "Feb 10, 2025",
    category: "Data Science",
    slug: "eda-insurance-claims-fraud",
    readTime: "7 min read",
    content: [
      { type: "p", text: "There's a temptation in data science to jump straight to modelling. Resist it. Every hour spent on EDA saves two hours of debugging a poorly performing model." },
      { type: "h2", text: "First Look at the Data" },
      { type: "p", text: "My first step was always a quick audit: shape, dtypes, null counts, and value distributions. The insurance dataset had 15,420 rows and 33 columns. Seven columns had missing values — notably police_report_available (18% missing) and property_damage (7% missing). I made deliberate imputation choices rather than dropping rows." },
      { type: "code", language: "python", text: "import pandas as pd\nimport seaborn as sns\nimport matplotlib.pyplot as plt\n\ndf = pd.read_csv('insurance_claims.csv')\nprint(df.isnull().sum().sort_values(ascending=False))\nprint(df['fraud_reported'].value_counts(normalize=True))" },
      { type: "h2", text: "Class Imbalance" },
      { type: "p", text: "The target column showed a 76/24 split (legitimate/fraud). This is moderate imbalance — not catastrophic, but enough to mislead a naive model into always predicting 'not fraud' and achieving 76% accuracy while being useless." },
      { type: "h2", text: "Univariate Analysis" },
      { type: "p", text: "I plotted distributions for every numeric feature, separated by fraud label. Some features showed almost no separation (e.g., age, months_as_customer). Others were immediately telling:" },
      { type: "ul", items: ["incident_severity: Major damage claims were disproportionately fraudulent.", "number_of_vehicles_involved: Single-vehicle incidents had lower fraud rates.", "bodily_injuries: Claims with 2+ injuries skewed heavily toward fraud."] },
      { type: "h2", text: "Correlation Heatmap" },
      { type: "p", text: "A Spearman correlation heatmap (used because several features were ordinal) highlighted that claim_amount, bodily_injuries, and incident_severity were positively correlated with each other and with fraud. Meanwhile, months_as_customer showed a weak negative correlation — longer-tenured customers were slightly less likely to commit fraud." },
      { type: "h2", text: "Categorical Analysis" },
      { type: "p", text: "For categorical features, I computed the fraud rate within each category. The standout finding: claims marked as having no police report had a fraud rate of 39%, versus 14% for claims with a police report filed. This single feature alone carries enormous predictive signal." },
      { type: "h2", text: "Outlier Detection" },
      { type: "p", text: "Using IQR-based outlier flagging, I identified 312 extreme claim amounts. Importantly, 68% of these outliers were labelled as fraudulent — the highest class ratio in any subset I examined. This validated the claim_to_premium_ratio feature I later engineered." },
      { type: "h2", text: "Takeaway" },
      { type: "p", text: "EDA is not just data cleaning. It's hypothesis generation. Every chart I made in this phase either confirmed a feature worth keeping or revealed one worth creating. Going into modelling with this context made the difference between a 78% and a 93% ROC-AUC score." },
    ],
  },
  {
    title: "XGBoost vs Extra Trees: Which Wins on Imbalanced Fraud Data?",
    excerpt:
      "I compared 5 ML algorithms on a highly imbalanced fraud dataset. This post dives into why XGBoost and Extra Trees outperformed simpler classifiers and how I tuned hyperparameters to push ROC-AUC beyond 0.93.",
    date: "Mar 5, 2025",
    category: "Machine Learning",
    slug: "xgboost-vs-extra-trees-fraud",
    readTime: "8 min read",
    content: [
      { type: "p", text: "When building the fraud detection system, choosing the right algorithm wasn't as simple as picking the most popular one. I ran a structured comparison across five classifiers and documented exactly why the top two pulled ahead." },
      { type: "h2", text: "Evaluation Framework" },
      { type: "p", text: "All models were evaluated using 5-fold stratified cross-validation on a consistent 80/20 train-test split. Metrics tracked: ROC-AUC, F1-score (weighted), Precision, Recall, and training time. SMOTE was applied inside each fold's training set to prevent data leakage." },
      { type: "h2", text: "Why Logistic Regression Fell Short" },
      { type: "p", text: "With a ROC-AUC of 0.71, Logistic Regression struggled because fraud patterns in this dataset are non-linear. Features like claim_to_premium_ratio interact multiplicatively with incident_severity — linear decision boundaries simply can't capture this. I tried adding polynomial features but the improvement was marginal (0.74) at the cost of much higher complexity." },
      { type: "h2", text: "Decision Tree — Good Intuition, Poor Generalisation" },
      { type: "p", text: "A tuned Decision Tree reached 0.78 ROC-AUC but showed high variance across folds (std dev of 0.06). Decision Trees overfit easily on tabular data with mixed feature types. They're great for explainability but not for production accuracy." },
      { type: "h2", text: "XGBoost — The Reliable Powerhouse" },
      { type: "p", text: "XGBoost achieved 0.91 ROC-AUC. Key hyperparameters that mattered most:" },
      { type: "ul", items: ["scale_pos_weight: Set to 3.16 (ratio of negatives to positives) to handle class imbalance natively.", "max_depth: 4 — shallow trees prevent overfitting on noisy fraud signals.", "learning_rate: 0.05 with 500 estimators and early stopping.", "subsample + colsample_bytree: Both at 0.8, introducing stochasticity."] },
      { type: "code", language: "python", text: "from xgboost import XGBClassifier\n\nxgb = XGBClassifier(\n    n_estimators=500,\n    max_depth=4,\n    learning_rate=0.05,\n    scale_pos_weight=3.16,\n    subsample=0.8,\n    colsample_bytree=0.8,\n    early_stopping_rounds=50,\n    eval_metric='auc',\n    random_state=42\n)" },
      { type: "h2", text: "Extra Trees — The Unexpected Winner" },
      { type: "p", text: "Extra Trees (Extremely Randomised Trees) beat XGBoost by a small margin: 0.9305 vs 0.91. The reason is subtle: unlike Random Forest which finds the optimal split threshold for each feature, Extra Trees picks split thresholds randomly. This extreme randomisation acts as a stronger regulariser — especially beneficial on noisy datasets like fraud claims where many features have overlapping distributions between classes." },
      { type: "p", text: "Extra Trees also trained ~4× faster than XGBoost, which matters in a real-time fraud scoring pipeline." },
      { type: "h2", text: "Final Verdict" },
      { type: "p", text: "For this specific dataset, Extra Trees won. But the gap was small enough that in a production system I'd ensemble both. The real lesson: always benchmark multiple algorithms rather than defaulting to XGBoost. Dataset characteristics determine the winner." },
    ],
  },
  {
    title: "Deploying an ML Model to Streamlit: A Step-by-Step Guide",
    excerpt:
      "After training the fraud detection model, I needed a fast way to demo it. Streamlit turned out to be perfect. This guide walks through packaging a Scikit-learn pipeline and serving real-time predictions.",
    date: "Apr 2, 2025",
    category: "Engineering",
    slug: "deploying-ml-streamlit",
    readTime: "6 min read",
    content: [
      { type: "p", text: "Training a model is only half the work. If no one can interact with it, it's just a file on your hard drive. Streamlit lets you build a fully functional ML demo in hours, not weeks." },
      { type: "h2", text: "Packaging the Model Pipeline" },
      { type: "p", text: "The key to a clean deployment is wrapping everything — preprocessor and model — into a single Scikit-learn Pipeline object before serialising. This means you never have to worry about applying transformations separately in production." },
      { type: "code", language: "python", text: "from sklearn.pipeline import Pipeline\nfrom sklearn.preprocessing import StandardScaler, OneHotEncoder\nfrom sklearn.compose import ColumnTransformer\nfrom sklearn.ensemble import ExtraTreesClassifier\nimport joblib\n\npreprocessor = ColumnTransformer([\n    ('num', StandardScaler(), numeric_features),\n    ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)\n])\n\npipeline = Pipeline([\n    ('preprocessor', preprocessor),\n    ('classifier', ExtraTreesClassifier(n_estimators=200, random_state=42))\n])\n\npipeline.fit(X_train, y_train)\njoblib.dump(pipeline, 'fraud_model.pkl')" },
      { type: "h2", text: "Building the Streamlit App" },
      { type: "p", text: "The app has three sections: an input form, a prediction output, and a SHAP explanation chart. Here's the core structure:" },
      { type: "code", language: "python", text: "import streamlit as st\nimport joblib\nimport pandas as pd\nimport shap\n\nmodel = joblib.load('fraud_model.pkl')\n\nst.title('Auto Insurance Fraud Detector')\n\nwith st.form('claim_form'):\n    premium = st.number_input('Annual Premium ($)', 500, 50000, 5000)\n    claim_amount = st.number_input('Total Claim Amount ($)', 100, 100000, 10000)\n    incident_severity = st.selectbox('Incident Severity', ['Minor', 'Major', 'Total Loss'])\n    police_report = st.selectbox('Police Report Filed?', ['YES', 'NO'])\n    submitted = st.form_submit_button('Predict')\n\nif submitted:\n    input_df = pd.DataFrame([{\n        'policy_annual_premium': premium,\n        'total_claim_amount': claim_amount,\n        'incident_severity': incident_severity,\n        'police_report_available': police_report,\n    }])\n    prob = model.predict_proba(input_df)[0][1]\n    st.metric('Fraud Probability', f'{prob:.1%}')" },
      { type: "h2", text: "Adding SHAP Explanations" },
      { type: "p", text: "SHAP (SHapley Additive exPlanations) tells users *why* a claim was flagged. For tree-based models, SHAP is fast and exact. I used a waterfall plot to show which features pushed the prediction toward or away from fraud." },
      { type: "h2", text: "Deployment" },
      { type: "p", text: "Streamlit Community Cloud makes deployment trivial — push to GitHub, connect the repo, and it's live. The only gotcha: ensure your requirements.txt pins exact versions of scikit-learn and xgboost, since minor version differences can break model loading." },
      { type: "h2", text: "Results" },
      { type: "p", text: "The app went live within 2 hours of finishing the model. Non-technical stakeholders could immediately interact with it, understand the predictions, and validate that the model's reasoning aligned with domain expertise. That validation loop is invaluable." },
    ],
  },
  {
    title: "Hate Speech Detection: Why Simple Models Aren't Enough",
    excerpt:
      "For my Online Speech Moderation project, I started with a basic Logistic Regression baseline, then moved through SimpleRNN and LSTM. This post explains why the step up to transformer models became necessary.",
    date: "May 14, 2025",
    category: "NLP",
    slug: "hate-speech-detection-model-progression",
    readTime: "8 min read",
    content: [
      { type: "p", text: "When I started the Online Speech Moderation project, I made a deliberate choice to build up from the simplest baseline. This approach taught me more about the problem than jumping straight to BERT would have." },
      { type: "h2", text: "The Problem" },
      { type: "p", text: "Hate speech and offensive language detection is a classification task on short text: given a tweet or comment, label it as 'hate speech', 'offensive', or 'neither'. The dataset I used contained ~25,000 labelled tweets. Class distribution: 5.8% hate speech, 77.4% offensive, 16.8% neither. The high offensive language rate creates a challenging three-class problem." },
      { type: "h2", text: "Baseline: TF-IDF + Logistic Regression" },
      { type: "p", text: "The first model was intentionally simple. TF-IDF vectors (max 10,000 features, unigrams + bigrams) fed into Logistic Regression. Accuracy: 89%. Sounds good — until you look at the confusion matrix. The model almost entirely failed on the minority 'hate speech' class, achieving only 0.41 F1. It was mostly learning to distinguish offensive from neither." },
      { type: "h2", text: "SimpleRNN — Sequential Context Helps, But Barely" },
      { type: "p", text: "Moving to a SimpleRNN with pre-trained GloVe embeddings added sequential context. Words are no longer treated as independent. Accuracy improved to 91%, and hate speech F1 jumped to 0.54. Progress — but the model still struggled with sarcasm and context-dependent slurs that change meaning based on surrounding words." },
      { type: "h2", text: "LSTM — Handling Long-Range Dependencies" },
      { type: "p", text: "LSTMs are designed to capture long-range dependencies through their cell state mechanism. On this task, accuracy reached 93% and hate speech F1 reached 0.67. The improvement over SimpleRNN was consistent — the LSTM was better at connecting pronoun references and contextual modifiers to the offensive term." },
      { type: "h2", text: "Where RNNs Break Down" },
      { type: "p", text: "Despite the improvements, all RNN-based models shared a fundamental limitation: they process text sequentially, making them unable to use future context when encoding a word. The phrase 'that's not what I meant' completely changes the interpretation of a preceding statement — but an LSTM reading left-to-right doesn't know what comes next when it processes 'what'." },
      { type: "p", text: "This is where transformers — specifically BERT's bidirectional attention — become essential. BERT reads the entire sentence simultaneously, allowing it to contextualise every token against every other token." },
      { type: "h2", text: "What I Learned" },
      { type: "ul", items: ["Don't dismiss baselines — TF-IDF + LR is a surprisingly strong and fast baseline for many NLP tasks.", "F1 on minority classes is more informative than overall accuracy for imbalanced datasets.", "Sequential models plateau on tasks requiring rich bidirectional context.", "The jump from LSTM to BERT was not just quantitative but qualitative — the model started understanding irony and context in ways RNNs simply couldn't."] },
    ],
  },
  {
    title: "Fine-Tuning BERT for Hate Speech Classification",
    excerpt:
      "BERT's contextual embeddings make it uniquely suited for nuanced language tasks. I'll show you how I fine-tuned bert-base-uncased on hate speech data, reaching 78% accuracy, and what trade-offs I encountered.",
    date: "Jun 20, 2025",
    category: "NLP",
    slug: "fine-tuning-bert-hate-speech",
    readTime: "10 min read",
    content: [
      { type: "p", text: "Fine-tuning BERT is one of those techniques that sounds complicated but is surprisingly accessible with the Hugging Face Transformers library. Here's exactly how I did it for the speech moderation project." },
      { type: "h2", text: "Why BERT?" },
      { type: "p", text: "BERT (Bidirectional Encoder Representations from Transformers) is pre-trained on massive text corpora using masked language modelling and next sentence prediction. This pre-training gives it a rich understanding of language context that no RNN trained from scratch on 25,000 tweets can match. Fine-tuning simply adapts this knowledge to our specific classification task." },
      { type: "h2", text: "Setup and Tokenisation" },
      { type: "code", language: "python", text: "from transformers import BertTokenizer, BertForSequenceClassification\nimport torch\n\ntokenizer = BertTokenizer.from_pretrained('bert-base-uncased')\n\ndef tokenize(texts, max_length=128):\n    return tokenizer(\n        texts,\n        padding='max_length',\n        truncation=True,\n        max_length=max_length,\n        return_tensors='pt'\n    )\n\ntrain_encodings = tokenize(X_train.tolist())\nval_encodings = tokenize(X_val.tolist())" },
      { type: "h2", text: "Model Architecture" },
      { type: "p", text: "BertForSequenceClassification adds a linear classification head on top of BERT's [CLS] token representation. For a 3-class problem, I set num_labels=3. The entire model — BERT backbone + classification head — is fine-tuned end-to-end." },
      { type: "code", language: "python", text: "model = BertForSequenceClassification.from_pretrained(\n    'bert-base-uncased',\n    num_labels=3\n)\nmodel.to(device)" },
      { type: "h2", text: "Training Strategy" },
      { type: "p", text: "Key decisions during training:" },
      { type: "ul", items: ["Learning rate: 2e-5 with linear warmup over first 10% of steps — standard for BERT fine-tuning.", "Batch size: 16 (constrained by GPU memory).", "Epochs: 4 — BERT fine-tuning typically converges fast. More epochs risk catastrophic forgetting of pre-trained knowledge.", "Optimizer: AdamW with weight decay of 0.01.", "Class weights: Applied to the loss function to address the hate speech minority class."] },
      { type: "h2", text: "Results vs Previous Models" },
      { type: "ul", items: ["Logistic Regression: 89% accuracy, 0.41 hate speech F1", "SimpleRNN: 91% accuracy, 0.54 hate speech F1", "LSTM: 93% accuracy, 0.67 hate speech F1", "BERT (fine-tuned): 78% accuracy*, 0.74 hate speech F1"] },
      { type: "callout", text: "Why did accuracy drop with BERT? The model became more conservative — it stopped confidently misclassifying borderline offensive content as 'neither', which hurt overall accuracy but improved detection of actual hate speech. For a content moderation system, this is the right trade-off." },
      { type: "h2", text: "Inference Considerations" },
      { type: "p", text: "BERT inference is ~20× slower than LSTM. For the Flask API, I used ONNX export and dynamic quantisation to reduce latency from ~800ms to ~120ms per prediction without meaningful accuracy loss." },
    ],
  },
  {
    title: "Building a Flask API for Real-Time Text Classification",
    excerpt:
      "Wrapping a trained BERT model inside a Flask REST API so it can serve predictions on demand. Covers model serialisation, request validation, and connecting the backend to a simple front-end interface.",
    date: "Aug 8, 2025",
    category: "Engineering",
    slug: "flask-api-text-classification",
    readTime: "7 min read",
    content: [
      { type: "p", text: "A trained model sitting in a Jupyter notebook isn't useful to anyone. The final step of the speech moderation project was wrapping the BERT classifier in a production-ready Flask API." },
      { type: "h2", text: "Project Structure" },
      { type: "code", language: "bash", text: "speech-moderation-api/\n├── app.py\n├── model/\n│   ├── bert_classifier.pt\n│   └── tokenizer/\n├── utils/\n│   ├── preprocess.py\n│   └── predict.py\n├── requirements.txt\n└── Procfile" },
      { type: "h2", text: "Loading the Model at Startup" },
      { type: "p", text: "Model loading should happen once at app startup, not on every request. I used Flask's application context for this:" },
      { type: "code", language: "python", text: "from flask import Flask, request, jsonify\nfrom transformers import BertTokenizer, BertForSequenceClassification\nimport torch\n\napp = Flask(__name__)\n\n# Load once at startup\ntokenizer = BertTokenizer.from_pretrained('./model/tokenizer')\nmodel = BertForSequenceClassification.from_pretrained('./model')\nmodel.eval()\n\nLABELS = ['hate_speech', 'offensive', 'neither']" },
      { type: "h2", text: "The Prediction Endpoint" },
      { type: "code", language: "python", text: "@app.route('/predict', methods=['POST'])\ndef predict():\n    data = request.get_json()\n    if not data or 'text' not in data:\n        return jsonify({'error': 'Missing text field'}), 400\n\n    text = data['text'].strip()\n    if len(text) < 3:\n        return jsonify({'error': 'Text too short'}), 400\n\n    inputs = tokenizer(\n        text,\n        return_tensors='pt',\n        truncation=True,\n        max_length=128,\n        padding=True\n    )\n\n    with torch.no_grad():\n        outputs = model(**inputs)\n        probs = torch.softmax(outputs.logits, dim=-1)[0]\n        predicted = torch.argmax(probs).item()\n\n    return jsonify({\n        'label': LABELS[predicted],\n        'confidence': round(probs[predicted].item(), 4),\n        'probabilities': {\n            label: round(prob.item(), 4)\n            for label, prob in zip(LABELS, probs)\n        }\n    })" },
      { type: "h2", text: "Input Validation and Error Handling" },
      { type: "p", text: "Production APIs need to handle bad input gracefully. I added validation for empty strings, non-string types, and excessively long inputs (truncated at 512 tokens by BERT anyway, but good to inform the caller). All errors return structured JSON with a descriptive message." },
      { type: "h2", text: "Performance Optimisation" },
      { type: "p", text: "BERT inference is slow by default. Two optimisations made a significant difference:" },
      { type: "ul", items: ["torch.no_grad(): Disables gradient computation during inference — reduces memory by ~40% and speeds up forward pass.", "Dynamic quantisation: Converts weight matrices to INT8. Applied with torch.quantization.quantize_dynamic, reducing model size by 3× and latency by ~30%."] },
      { type: "h2", text: "Testing the API" },
      { type: "code", language: "bash", text: 'curl -X POST http://localhost:5000/predict \\\n  -H "Content-Type: application/json" \\\n  -d \'{"text": "I hate everything about this"}\'' },
      { type: "h2", text: "Deployment" },
      { type: "p", text: "The app was deployed to Heroku via a Procfile. One important caveat: Heroku's free dynos sleep after 30 minutes of inactivity, causing a cold-start delay on the first request. For production, a paid dyno or a platform like Railway is preferable." },
    ],
  },
  {
    title: "15 SQL Queries That Revealed Hidden Insights in Superstore Data",
    excerpt:
      "Using MySQL on the Superstore dataset, I wrote complex window functions, CTEs, and aggregation queries to surface business patterns that plain dashboards miss. A deep dive into analytical SQL for data science.",
    date: "Oct 3, 2025",
    category: "Data Analytics",
    slug: "sql-superstore-insights",
    readTime: "11 min read",
    content: [
      { type: "p", text: "The Superstore dataset contains nearly 10,000 transactions across 4 years. On the surface it looks simple. But with the right SQL queries, it reveals nuanced patterns about regional performance, customer lifetime value, and product profitability that no auto-generated dashboard would show you." },
      { type: "h2", text: "The Dataset" },
      { type: "p", text: "9,994 rows. 21 columns. Orders spanning 2018–2021 across 49 US states. Three product categories: Furniture, Office Supplies, Technology. Four customer segments: Consumer, Corporate, Home Office, Small Business." },
      { type: "h2", text: "1. Year-over-Year Revenue Growth by Category" },
      { type: "code", language: "sql", text: "SELECT\n  category,\n  YEAR(order_date) AS year,\n  ROUND(SUM(sales), 2) AS total_sales,\n  ROUND(\n    (SUM(sales) - LAG(SUM(sales)) OVER (PARTITION BY category ORDER BY YEAR(order_date)))\n    / LAG(SUM(sales)) OVER (PARTITION BY category ORDER BY YEAR(order_date)) * 100, 2\n  ) AS yoy_growth_pct\nFROM orders\nGROUP BY category, YEAR(order_date)\nORDER BY category, year;" },
      { type: "p", text: "Finding: Technology grew 31% YoY in 2021, while Furniture declined 4%. Office Supplies remained flat." },
      { type: "h2", text: "2. Most Profitable Products (Not Just Highest Revenue)" },
      { type: "code", language: "sql", text: "SELECT\n  product_name,\n  ROUND(SUM(sales), 2) AS total_sales,\n  ROUND(SUM(profit), 2) AS total_profit,\n  ROUND(SUM(profit) / SUM(sales) * 100, 2) AS profit_margin_pct\nFROM orders\nGROUP BY product_name\nORDER BY total_profit DESC\nLIMIT 10;" },
      { type: "p", text: "Finding: The Canon imageCLASS 2200 was the #1 product by profit ($25,199) despite not being the highest revenue item. Several high-revenue furniture items had negative profit margins." },
      { type: "h2", text: "3. Customer Retention via Cohort Analysis" },
      { type: "code", language: "sql", text: "WITH first_order AS (\n  SELECT customer_id, MIN(YEAR(order_date)) AS cohort_year\n  FROM orders\n  GROUP BY customer_id\n)\nSELECT\n  f.cohort_year,\n  YEAR(o.order_date) AS order_year,\n  COUNT(DISTINCT o.customer_id) AS active_customers\nFROM orders o\nJOIN first_order f ON o.customer_id = f.customer_id\nGROUP BY f.cohort_year, YEAR(o.order_date)\nORDER BY f.cohort_year, order_year;" },
      { type: "p", text: "Finding: 2018 cohort retained 43% of customers through 2021. 2020 cohort showed the strongest year-1 retention at 61%, likely influenced by remote work driving office supply demand." },
      { type: "h2", text: "4. Regional Discount Abuse" },
      { type: "code", language: "sql", text: "SELECT\n  region,\n  ROUND(AVG(discount), 3) AS avg_discount,\n  ROUND(SUM(profit), 2) AS total_profit,\n  SUM(CASE WHEN profit < 0 THEN 1 ELSE 0 END) AS loss_making_orders\nFROM orders\nGROUP BY region\nORDER BY avg_discount DESC;" },
      { type: "p", text: "Finding: The Central region had the highest average discount (0.31) and the most loss-making orders (783). Reducing Central discounts by 10% would have saved ~$42,000 in losses." },
      { type: "h2", text: "Key Takeaways from All 15 Queries" },
      { type: "ul", items: ["Revenue ≠ Profit. Several best-selling products destroyed margin.", "Window functions (LAG, RANK, NTILE) unlock temporal and comparative analysis impossible with simple GROUP BY.", "CTEs make complex queries readable and maintainable.", "The most actionable insights came from combining multiple dimensions — e.g., region + discount + profit.", "Cohort analysis revealed that acquisition year significantly predicted long-term customer value."] },
    ],
  },
  {
    title: "From SQL to Tableau: Building 8 Interactive Sales Dashboards",
    excerpt:
      "After extracting insights via SQL, I visualised them in Tableau. This post covers dashboard design principles, choosing the right chart types, and how I structured the Superstore analysis for stakeholder storytelling.",
    date: "Dec 12, 2025",
    category: "Data Analytics",
    slug: "sql-to-tableau-superstore-dashboards",
    readTime: "8 min read",
    content: [
      { type: "p", text: "SQL tells you what the data says. Tableau tells the story to everyone else. After extracting 15 key insights from the Superstore dataset, I translated them into 8 interactive dashboards designed for a non-technical business audience." },
      { type: "h2", text: "Dashboard Design Principles I Followed" },
      { type: "ul", items: ["One question per dashboard: Each dashboard answers exactly one business question. Mixing questions creates confusion.", "Most important metric top-left: Viewers scan in an F-pattern. Put the headline number where eyes land first.", "Consistent colour encoding: Green = profit/growth, Red = loss/decline. Never deviate from this throughout the workbook.", "Interactivity over static: Every dashboard has at least one filter (year, region, or category) so stakeholders can self-serve.", "Annotations for key events: A spike in Q4 2020 sales is meaningless without context. I annotated it with 'COVID remote work surge'."] },
      { type: "h2", text: "Dashboard 1: Executive Sales Overview" },
      { type: "p", text: "A single-page summary with four KPI tiles (Total Sales, Total Profit, Orders, Avg Discount), a line chart of monthly revenue with a trend line, and a filled map of sales by state. This was the landing page — designed to be understandable in 10 seconds." },
      { type: "h2", text: "Dashboard 2: Category Performance Deep Dive" },
      { type: "p", text: "A bar chart race showing category sales over time, paired with a scatter plot of discount rate vs profit margin per sub-category. This directly visualised the 'high discount = low profit' relationship from the SQL analysis. The scatter plot had a clear negative correlation — immediately actionable for a sales team." },
      { type: "h2", text: "Dashboard 3: Regional Profitability Heatmap" },
      { type: "p", text: "A state-level heatmap (filled map) with profit margin as the colour measure. Users could filter by product category to see which states were profitable for Technology but losing money on Furniture. This highlighted that the Central region's furniture sales were systematically unprofitable." },
      { type: "h2", text: "Dashboard 4: Customer Segment Analysis" },
      { type: "p", text: "Four donut charts (one per segment) showing the revenue and order count split, alongside a bar chart of average order value by segment. Corporate customers had 23% higher AOV than Consumers but represented only 19% of orders — a clear signal to invest in corporate account development." },
      { type: "h2", text: "Dashboard 5: Product Profitability Matrix" },
      { type: "p", text: "A bubble chart with Sales on X, Profit on Y, and bubble size = order quantity. Products in the top-right quadrant (high sales, high profit) are stars. Bottom-left are dead weight. Several Furniture products sat in the top-left (high sales, negative profit) — a product management red flag." },
      { type: "h2", text: "The Storytelling Structure" },
      { type: "p", text: "I organised the dashboards as a story arc: Start with the big picture (Dashboard 1), zoom in on problems (Dashboards 2–4), diagnose root causes (Dashboards 5–7), and end with recommendations (Dashboard 8). This mirrors how a business analyst would present findings to a C-suite audience." },
      { type: "h2", text: "Lessons Learned" },
      { type: "ul", items: ["Tableau's dashboard layout containers are powerful but frustrating — build mobile-last, desktop-first.", "Calculated fields in Tableau can replace many SQL queries, but complex CTEs are better done in SQL before connecting to Tableau.", "The hardest part of data visualisation is deciding what NOT to show. Every chart you remove makes the remaining ones more impactful.", "Publish to Tableau Public early and share with stakeholders — their feedback reshaped 3 of my 8 dashboards completely."] },
    ],
  },
  {
    title: "Lessons Learned: Three ML Projects, One Year of Growth",
    excerpt:
      "A reflective look at what I learned building fraud detection, hate speech moderation, and superstore analytics systems. Honest observations on model selection mistakes, deployment hurdles, and what I'd do differently.",
    date: "Jun 15, 2026",
    category: "Career",
    slug: "ml-projects-year-in-review",
    readTime: "9 min read",
    content: [
      { type: "p", text: "A year ago I started three projects with the goal of building a complete data science portfolio. Looking back, the code was the easy part. Here's what I actually learned." },
      { type: "h2", text: "Project 1: Auto Insurance Fraud Detection" },
      { type: "p", text: "What went well: The model pipeline was clean and reproducible. SHAP integration made it explainable. Streamlit deployment happened fast." },
      { type: "p", text: "What I'd do differently: I underestimated the time spent on data cleaning versus modelling. In hindsight, 60% of the value came from the EDA and feature engineering phase, yet I'd allocated only 20% of my time there. I'd now flip that ratio." },
      { type: "callout", text: "The model only improved 3 ROC-AUC points from my second-best feature set to my final one. But the first feature set I tried (raw features, no engineering) was 12 points behind. Feature engineering is where you earn the wins." },
      { type: "h2", text: "Project 2: Online Speech Moderation" },
      { type: "p", text: "What went well: The progressive model comparison (LR → RNN → LSTM → BERT) gave me a deep understanding of why each architecture exists. Most people skip straight to BERT — I'm glad I didn't." },
      { type: "p", text: "What I'd do differently: The Flask API deployment was scrappy. I didn't add rate limiting, authentication, or proper logging. A production API needs all three. I also underestimated inference latency — serving BERT in real-time requires quantisation or distillation, which I only addressed after deployment." },
      { type: "h2", text: "Project 3: Superstore Sales Analysis" },
      { type: "p", text: "What went well: The SQL-first approach was the right call. Writing queries before opening Tableau forced me to think analytically about the data before thinking visually. The insights were sharper as a result." },
      { type: "p", text: "What I'd do differently: I spent too long making dashboards look polished when the analytical depth wasn't fully there yet. Substance before aesthetics. A rough dashboard with profound insight beats a beautiful dashboard with obvious observations every time." },
      { type: "h2", text: "Cross-Project Lessons" },
      { type: "ul", items: [
        "Documentation is not optional. I lost two days re-understanding my own code because I hadn't commented a preprocessing step. Write for your future self.",
        "Version control everything from day one. I lost an early feature engineering notebook that wasn't committed. Lesson permanently learned.",
        "The gap between 'model works' and 'model is deployed and useful' is larger than you think. Budget time for it.",
        "Share your work publicly early. The feedback I got on GitHub and Tableau Public improved all three projects significantly.",
        "Domain knowledge matters as much as technical skill. Understanding insurance fraud patterns made me a better data scientist on that project than any algorithm choice did."
      ] },
      { type: "h2", text: "What's Next" },
      { type: "p", text: "The next year will focus on deeper work: time-series forecasting, LLM fine-tuning on domain-specific data, and building end-to-end MLOps pipelines. The foundation is solid. Time to build something harder." },
    ],
  },
];

export function getPostBySlug(slug: string): BlogPost | undefined {
  return blogPosts.find((post) => post.slug === slug);
}
